config/routes.rb
Blog::Application.routes.draw do
  resources :comments

  resources :pages

  resources :articles

  devise_for :users

  match 'tags/:id', :to => 'articles#index', :as => 'article_by_tag', :format => false

  match ':year/:month', :to => 'articles#index', :year => /\d{4}/, :month => /\d{1,2}/, :as => 'articles_by_month', :format => false

  match 'admin', :to  => 'admin/contents#index', :format => false

  root :to => 'articles#index'

  %w{categories comments contents pages tags }.each do |i|
    match "/admin/#{i}", :to => "admin/#{i}#index", :format => false
    match "/admin/#{i}(/:action(/:id))", :to => "admin/#{i}", :action => nil, :id => nil, :format => false
  end

end

app/models/article.rb
class Article < Content
  def self.archives
    date_func = "extract(year from created_at) as year,extract(month from created_at) as month"

    article_counts = Content.find_by_sql(["select count(*) as count, #{date_func} from contents where type='Article' and created_at < ? group by year,month order by year desc,month desc limit ? ",Time.now,count.to_i])

    archives = article_counts.map do |entry|
      {
        :name => Date::MONTHNAMES[entry.month.to_i] + " #{entry.year}",
        :month => entry.month.to_i,
        :year => entry.year.to_i,
        :article_count => entry.count
      }
    end
    archives
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = params[:id] ? Article.tagged_with(Tag.find(params[:id]).name) : Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Article</legend>

    <div class="control-group">
      <%= f.label :type, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :type, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :author, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :author, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :body, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :body, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :extended, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :extended, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :excerpt, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :excerpt, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :user_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :user_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :permalink, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :permalink, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :guid, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :guid, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :text_filter_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :text_filter_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :whiteboard, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :whiteboard, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :published, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :published, :class => 'check_box' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :allow_pings, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :allow_pings, :class => 'check_box' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :allow_comments, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :allow_comments, :class => 'check_box' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :published_at, :class => 'control-label' %>
      <div class="controls">
        <%= f.datetime_select :published_at, :class => 'datetime_select' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :state, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :state, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :parent_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :parent_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :settings, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :settings, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :post_type, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :post_type, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', articles_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/articles/edit.html.erb
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
    <% @articles.each_with_index do |article, index| %>
            <div class="span4">
              <h2><%= article.title %></h2>
              <p><%= article.excerpt %></p>
              <p><%= link_to 'View details >>', article, :class => 'btn' %></p>
            </div><!--/span-->
    <% if index % 3 == 2 %>
          </div><!--/row-->
          <div class="row-fluid">
    <% end %>
    <% end %>

app/views/articles/new.html.erb
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
  <%= @article.body %>
</p>

  <div class='meta'>
    <p>
      <small>Published on
        <%= @article.created_at.to_date %>
        .
        Tags 
        <% for tag in @article.tags %>
        <a href="<%= article_by_tag_path(tag) %>" rel="tag"><%= tag.name %></a>
        <% end %>
      </small>
      </p>
    </div>

    <h3 class="feedback" id="commentaires">
      <%= @article.comments.count %> comment &raquo;
    </h3>
    <ul id="commentList" class="unstyled">

<% for comment in @article.comments %>
  <li id="comment-1">
  <h4>
    By <%= comment.name %>
    <%= comment.created_at.to_date %>
  </h4>
    <p><%= comment.comment %></p>
  <hr />
</li>
<% end %>

</ul>

    <%= render 'comments/form' %>