config/routes.rb
Blog::Application.routes.draw do
  resources :comments

  resources :pages

  resources :articles

  devise_for :users

  match 'tags/:id', :to => 'articles#index', :as => 'article_by_tag', :format => false

  match ':year/:month', :to => 'articles#index', :year => /\d{4}/, :month => /\d{1,2}/, :as => 'articles_by_month', :format => false

  match 'admin', :to  => 'admin/contents#index', :format => false

  root :to => 'articles#index'

  %w{categories comments contents pages tags }.each do |i|
    match "/admin/#{i}", :to => "admin/#{i}#index", :format => false
    match "/admin/#{i}(/:action(/:id))", :to => "admin/#{i}", :action => nil, :id => nil, :format => false
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">

          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Blog</a>
          <div class="nav-collapse">
            <% if user_signed_in? %>
            <p class="navbar-text pull-right">Signed in as <a href="<%= admin_path %>"><%= current_user.email %></a> <a href="<%= destroy_user_session_path %>">Sign out</a></p>
            <% else %>
            <p class="navbar-text pull-right"><a href="<%= admin_path %>">Sign in</a></p>
            <% end %>
          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">

              <li class="nav-header"><a href="<%= admin_contents_path %>">Articles</a></li>
              <li><a href="<%= admin_contents_path %>/new">New Article</a></li>
              <li><a href="<%= admin_comments_path %>">Comments</a></li>
              <li><a href="<%= admin_tags_path %>">Tags</a></li>

              <li class="nav-header"><a href="<%= admin_pages_path %>">Pages</a></li>
              <li><a href="<%= admin_pages_path %>/new">New Page</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->

        <div class="span9">
          <div class="hero-unit">

            <%= yield %>

          </div><!--/row-->
        </div><!--/span-->

      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">

          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Blog</a>
          <div class="nav-collapse">
            <ul class="nav">
  <% Page.all.each do |page| %>
              <li><a href="<%= page_path(page) %>"><%= page.title %></a></li>
  <% end %>
            </ul>
            <% if user_signed_in? %>
            <p class="navbar-text pull-right">Signed in as <a href="<%= admin_path %>"><%= current_user.email %></a> <a href="<%= destroy_user_session_path %>">Sign out</a></p>
            <% else %>
            <p class="navbar-text pull-right"><a href="<%= admin_path %>">Sign in</a></p>
            <% end %>
          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">

              <li class="nav-header">Pages</li>
  <% Page.all.each do |page| %>
              <li><a href="<%= page_path(page) %>"><%= page.title %></a></li>
  <% end %>

              <li class="nav-header">Archives</li>
  <% Article.archives.each do |month| %>
    <% counter = "<em>(#{month[:article_count]})</em>" %>
    <li>
      <%= link_to"#{month[:name]} #{counter}".html_safe, articles_by_month_path(month[:year], "%02i" % month[:month]) %>
    </li>
  <% end %>

              <li class="nav-header">Tags</li>
  <% Tag.all.each do |tag| %>
              <li><a href="<%= article_by_tag_path(tag) %>"><%= tag.name %></a></li>
  <% end %>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->

        <div class="span9">
            <img src="/assets/hero.png">
<!--            <h1>Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>-->
          <div class="row-fluid">

            <%= yield %>

          </div><!--/row-->
        </div><!--/span-->

      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>